name: newenv
dependencies:
- enum34=1.1.6=py27_0
- funcsigs=1.0.2=py27_0
- futures=3.0.5=py27_0
- llvmlite=0.12.1=py27_0
- mkl=11.3.3=0
- numba=0.27.0=np111py27_0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=25.1.6=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - certifi==2016.2.28
  - configparser==3.5.0
  - decorator==4.0.10
  - entrypoints==0.2.2
  - functools32==3.2.3.post2
  - ipykernel==4.3.1
  - ipython==5.0.0
  - ipython-genutils==0.1.0
  - ipython-sql==0.3.6
  - ipywidgets==5.1.5
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - markupsafe==0.23
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.0.1
  - notebook==4.2.1
  - pathlib2==2.1.0
  - pexpect==4.2.0
  - pickleshare==0.7.2
  - prettytable==0.7.2
  - prompt-toolkit==1.0.3
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyzmq==15.3.0
  - qtconsole==4.2.1
  - simplegeneric==0.8.1
  - sqlalchemy==1.0.14
  - sqlparse==0.1.19
  - terminado==0.6
  - tornado==4.3
  - traitlets==4.2.2
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.3
prefix: /home/bryanhe/.conda/envs/newenv

